-- user
CREATE USER admin WITH ENCRYPTED PASSWORD 'secret';

-- database
CREATE DATABASE account;
GRANT ALL PRIVILEGES ON DATABASE account TO admin;

CREATE DATABASE tradelog;
GRANT ALL PRIVILEGES ON DATABASE tradelog TO admin;

CREATE DATABASE stockdata;
GRANT ALL PRIVILEGES ON DATABASE stockdata TO admin;

-- CREATE DATABASE timesheet;
-- GRANT ALL PRIVILEGES ON DATABASE timesheet TO admin;

-- CREATE DATABASE customer;
-- GRANT ALL PRIVILEGES ON DATABASE customer TO admin;

