-- user
DROP USER IF EXISTS admin;
CREATE USER admin WITH ENCRYPTED PASSWORD 'secret';

-- database
CREATE DATABASE account;
GRANT ALL PRIVILEGES ON DATABASE account TO admin;

CREATE DATABASE tenant;
GRANT ALL PRIVILEGES ON DATABASE tenant TO admin;

CREATE DATABASE customer;
GRANT ALL PRIVILEGES ON DATABASE customer TO admin;

CREATE DATABASE core;
GRANT ALL PRIVILEGES ON DATABASE core TO admin;

CREATE DATABASE stockdata;
GRANT ALL PRIVILEGES ON DATABASE stockdata TO admin;